import { StyleSheet } from 'react-native';
import { colors, ios } from '../../theme';

export const accountStyles = StyleSheet.create({
  shell: {
    flex: 1,
    backgroundColor: colors.surface,
  },
  content: {
    paddingTop: 4,
    paddingBottom: 32,
    flexGrow: 1,
  },
  navHeader: {
    backgroundColor: colors.surface,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
    paddingHorizontal: 16,
    paddingBottom: 12,
  },
  navTrack: {
    flexDirection: 'row',
    backgroundColor: colors.bg,
    borderRadius: 10,
    padding: 3,
    borderWidth: 1,
    borderColor: colors.border,
  },
  navItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    paddingHorizontal: 2,
    borderRadius: 7,
    minHeight: 34,
  },
  navItemPressed: {
    opacity: 0.75,
  },
  navItemActive: {
    backgroundColor: colors.surface,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 1,
  },
  navItemText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.muted,
    textAlign: 'center',
  },
  navItemTextActive: {
    color: colors.primary,
    fontWeight: '700',
  },
  mainScroll: {
    flex: 1,
  },
  mainTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: colors.text,
    letterSpacing: -0.3,
    marginTop: 8,
    marginBottom: 12,
    paddingHorizontal: 16,
  },
  fieldList: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
    marginHorizontal: 16,
  },
  field: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  fieldRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    gap: 10,
    minHeight: 56,
  },
  fieldBody: {
    flex: 1,
    minWidth: 0,
  },
  fieldLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
  },
  fieldValue: {
    fontSize: 14,
    color: colors.text,
    marginTop: 2,
  },
  fieldValuePlaceholder: {
    color: colors.muted,
  },
  fieldEditor: {
    paddingBottom: 14,
  },
  sectionHint: {
    fontSize: 13,
    color: colors.muted,
    marginTop: 12,
    marginHorizontal: 16,
    lineHeight: 18,
  },
  photoWrap: {
    marginHorizontal: 16,
    marginBottom: 16,
    alignItems: 'flex-start',
  },
  photoBtn: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: '#e5e5e5',
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  photoImage: {
    width: '100%',
    height: '100%',
  },
  photoInitials: {
    fontSize: 22,
    fontWeight: '700',
    color: '#737373',
  },
  photoOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15, 23, 42, 0.55)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  photoEdit: {
    marginTop: 10,
    backgroundColor: ios.buttonGray,
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 20,
    minHeight: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  photoEditText: {
    fontSize: 17,
    fontWeight: '600',
    color: colors.text,
  },
  photoEditPressed: {
    backgroundColor: ios.buttonGrayPressed,
  },
  saveBar: {
    marginTop: 20,
    paddingTop: 16,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
    marginHorizontal: 16,
    paddingHorizontal: 0,
  },
  saveBtn: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    paddingVertical: 14,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveBtnDisabled: {
    opacity: 0.6,
  },
  saveBtnText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 17,
  },
  successText: {
    color: colors.success,
    marginBottom: 12,
    fontWeight: '600',
  },
  errorText: {
    color: colors.danger,
    marginBottom: 12,
  },
  phoneRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    backgroundColor: colors.surface,
    overflow: 'hidden',
  },
  phonePrefix: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 15,
    fontWeight: '600',
    color: colors.muted,
    backgroundColor: colors.bg,
    borderRightWidth: 1,
    borderRightColor: colors.border,
  },
  phoneInput: {
    flex: 1,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 16,
    color: colors.text,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    padding: 12,
    fontSize: 15,
    color: colors.text,
    backgroundColor: colors.surface,
  },
  textArea: {
    minHeight: 88,
    paddingTop: 12,
    textAlignVertical: 'top',
  },
  editorLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.muted,
    marginBottom: 6,
  },
  editorHint: {
    fontSize: 13,
    color: colors.muted,
    marginBottom: 8,
    lineHeight: 18,
  },
  linkBtn: {
    alignSelf: 'stretch',
    marginTop: 10,
    backgroundColor: ios.buttonGray,
    borderRadius: 12,
    paddingVertical: 13,
    paddingHorizontal: 16,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  linkBtnPressed: {
    backgroundColor: ios.buttonGrayPressed,
  },
  linkBtnText: {
    fontSize: 17,
    fontWeight: '600',
    color: colors.text,
  },
  dangerLink: {
    color: colors.danger,
    fontWeight: '600',
    fontSize: 14,
    marginTop: 4,
  },
  chipWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 4,
  },
  chip: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.bg,
  },
  chipActive: {
    backgroundColor: '#eff6ff',
    borderColor: colors.primary,
  },
  chipText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.text,
  },
  chipTextActive: {
    color: colors.primary,
  },
  segmentRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 4,
  },
  segment: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.bg,
    alignItems: 'center',
  },
  segmentActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  segmentText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
  },
  segmentTextActive: {
    color: '#fff',
  },
  serviceAreaInputRow: {
    position: 'relative',
  },
  serviceAreaInput: {
    minHeight: 48,
    paddingRight: 36,
  },
  serviceAreaClear: {
    position: 'absolute',
    right: 10,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
  },
  serviceAreaActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 10,
  },
  serviceAreaBtn: {
    flex: 1,
    paddingVertical: 13,
    paddingHorizontal: 12,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 44,
  },
  serviceAreaBtnPrimary: {
    backgroundColor: colors.primary,
  },
  serviceAreaBtnPrimaryText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 17,
  },
  serviceAreaBtnSecondary: {
    backgroundColor: ios.buttonGray,
  },
  serviceAreaBtnSecondaryText: {
    color: colors.text,
    fontWeight: '600',
    fontSize: 17,
  },
  serviceAreaBtnPressed: {
    opacity: 0.85,
  },
  serviceAreaBtnSecondaryPressed: {
    backgroundColor: ios.buttonGrayPressed,
  },
  loadingWrap: {
    paddingVertical: 32,
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 8,
    color: colors.muted,
    fontSize: 14,
  },
});
